### ISSUE TITLE
Demo ?

### ISSUE THREAD

**Issue by s0kil** [zaceno/hypercraft#1]

**Comment by zaceno** [comment]
@DanielSokil, please elaborate! Demo what?

**Comment by zaceno** [comment]
@DanielSokil Did you mean: where to read the blog online? Yeah, that's not clear I guess if you come to the repo via github. It's at https://zaceno.github.io/hypercraft

I'll add a Readme.md with a link to make it clear :)

**Comment by s0kil** [comment]
@zaceno Yes. Thanks!
